### ISSUE TITLE
Line 86

### ISSUE THREAD

**Issue by knoxh** [knoxh/Twitter#5]
Line 86 won't work anymore. I tried rbind, and changing other little things. I understand that the column we want to change is user$id and we want to add originalTweeter, but I'm not sure why this code won't work. I thought it worked earlier? All I changed was "originalUser" to "originalTweeter" because we changed the name. 
The code is in my rtweet file, but I'm not sure how to add that to this "Issue."
Thank you!
@gdancik

**Comment by gdancik** [comment]
I'm not sure why it was working before, but the issue is that you are adding a new element to a single column of a data frame (rather than adding a new row to the data frame). Perhaps the easiest way is to use the _dplyr_ library and then the command:

who_retweet <- bind_rows(originalTweeter, who_retweet)
